### ISSUE TITLE
Changing backend to MESA

### ISSUE THREAD

**Issue by bangxiangyong** [bangxiangyong/agentMET4FOF#113]
Considering the issues faced in current implementation of the agents with osbrain:

- Lack of capability to attach python debugger on agent
- Slow spawning of agent process on Windows 
- Each agent occupies much memory

I am seriously considering we may migrate the backend to PADE: https://pade.readthedocs.io/en/latest/

Edit: After tinkering with PADE, i've found it to be non-suitable for update case, and has decided to stick to implementing MESA instead.

Initial run of their "hello world" suggests all of the above issues are alleviated.

**Comment by BjoernLudwigPTB** [comment]
Have you actually tried the debugging? That would be a major improvement regarding some of our trouble in the past and currently.

**Comment by bangxiangyong** [comment]
Yes i have tried simple debugging via pycharm, i could stop at the breakpoints.

**Comment by bangxiangyong** [comment]
After much tinkering on my local repo with PADE, i find it unsuitable to fully replace osbrain due to:

1. support for distributed computing is lacking 
2. lack of remote object interface, makes it hard to access the launched agents as python objects from dashboard server/or other terminals (which relates to 1.)

Nonetheless, we might explore an option for users who only want to quickly develop agents on a single machine (non-distributed) without the above issues of debugging, slow starting, etc. Then, once the agents are working as intended on a single machine, users can swap the backend back to osbrain for enabling distributed computing.

**Comment by BjoernLudwigPTB** [comment]
That sounds like a brilliant idea to me, as long, as we are able to encapsulate the different backends in a way, that ensures, that always both are running. Of course, if we start developing something we would simply start to test all our cases against both backends and monitor matching results.

**Comment by BjoernLudwigPTB** [comment]
That appears to be resolved by merging #120, right?

**Comment by BjoernLudwigPTB** [comment]
> That appears to be resolved by merging #120, right?

I just noticed your comment in the PR. The automagically GitHub mechanism only works for one the issue directly following the key word. To Automatically resolve several issues you would have to add one keyword per issue #. I'm closing this one now...
