### ISSUE TITLE
Plots no longer generated in tutorial_4_metrological_agents.py

### ISSUE THREAD

**Issue by anupam-prasad** [bangxiangyong/agentMET4FOF#131]
The MetrologicalMonitorAgent receives the correct data, but the plot of the sine function is no longer generated.

**Comment by BjoernLudwigPTB** [comment]
Which commit/release and what setup are you working on?

**Comment by anupam-prasad** [comment]
The one that I'm working on is even with bangxiangyong/develop

**Comment by BjoernLudwigPTB** [comment]
> The one that I'm working on is even with bangxiangyong/develop

So you are on f1c96a3c and you are using a Windows 10 machine with Python 3.8?

**Comment by anupam-prasad** [comment]
Yes, I'm on Windows 10 with Python 3.8. I didn't have a version of agentMET4FOF installed in my virtual environment, but I have one now.

I'm following the README way of executing the tutorials. Running the script and opening http://127.0.0.1:8050 on a browser. The dashboard appears with the agents and the plot-axes, but the plot isn't generated.

**Comment by bangxiangyong** [comment]
even with the 'mesa' backend, it's not working at this point on tut4

**Comment by BjoernLudwigPTB** [comment]
Resolved by #136
