### ISSUE TITLE
Handling of customized initialization process

### ISSUE THREAD

**Issue by mgrub** [bangxiangyong/agentMET4FOF#133]
How should a customized initialization process be handled ideally? We were thinking of two different ways, but both impose some problems.

## using `init_parameters(...)`

During the use of this agent-framework in some of our use-cases we noticed, that the `init_parameters()`-method gets called twice - once within the agent-initialization and once explicitly by us. However, during the first one, it is only called with the default parameters. (In our case, the `init_parameters()` receives metadata about itself from some server. Calling it with the default parameters result in a mere timeout that delays the whole initialization process.)

This is presented in the MWE `main_1`.

## using `add_agent(..., **kwargs)`

Probably the intented way, but results in a `TypeError`. 

This is presented in MWE `main_2`.

## minimum working example

```python
from agentMET4FOF.agents import AgentMET4FOF, AgentNetwork


class CustomAgent(AgentMET4FOF):
    def init_parameters(self, foo="default call"):
        self.foo = foo

        # logging
        msg = 'Agent is initialized with foo == "{}"'.format(foo)
        print(msg)
        self.log_info(msg)

    def agent_loop(self):
        if self.current_state == "Running":
            # logging
            msg = 'Agent is running with self.foo == "{}"'.format(self.foo)
            print(msg)
            self.log_info(msg)


def main_1():

    agent_network = AgentNetwork(dashboard_modules=False)

    custom_agent = agent_network.add_agent(name="custom_agent", agentType=CustomAgent)
    custom_agent.init_parameters(foo="custom call")
    agent_network.set_running_state()

    return agent_network

def main_2():

    agent_network = AgentNetwork(dashboard_modules=False)

    kwargs = {"foo": "custom call"}
    custom_agent = agent_network.add_agent(name="custom_agent", agentType=CustomAgent, **kwargs)
    agent_network.set_running_state()

    return agent_network


if __name__ == "__main__":
    # works, but double call of init_parameters()
    main_1()
    
    # doesn't work, raises TypeError
    # main_2()

```

PS: Although all logging was done using the same `self.log_info(...)`, the 'default call' is not tracked in the `log_file.csv` (but on the CLI-output).

**Comment by anupam-prasad** [comment]
I'm currently working on a branch that is even with f1c96a3c7b2dcaeb7f453af0f57a9b8adefcbfe1 and was able to run both main_1() and main_2() without errors.

**Comment by mgrub** [comment]
> 
> 
> I'm currently working on a branch that is even with [f1c96a3](https://github.com/bangxiangyong/agentMET4FOF/commit/f1c96a3c7b2dcaeb7f453af0f57a9b8adefcbfe1) and was able to run both main_1() and main_2() without errors.

That sounds great 😃 

So the approach examplified by `main_2()` showcases the inteneded use of a customized `agents.init_parameters()`?

**Comment by anupam-prasad** [comment]
> So the approach examplified by main_2() showcases the inteneded use of a customized agents.init_parameters()?

It certainly seems to. The implementation of AgentNetwork.add_agent is different in the latest commit though.

**Comment by bangxiangyong** [comment]
Yes indeed, main_1() was the earlier implementation in which main_2() is actually more intuitive. and yes, this is already made possible in the latest commit. 
then again, this could be improved by passing *args as well, instead just **kwargs, which has been addressed in @anupam-prasad recent pull request
