### ISSUE TITLE
Enable more than one Scatter by custom_plot_function

### ISSUE THREAD

**Issue by DigitalRev0lution** [bangxiangyong/agentMET4FOF#135]
Changing the line:
`data.append(custom_plot_function(memory_data[sender_agent],sender_agent,**custom_plot_parameters))`
in Dashboard_agt_net.py
to:
`data.extend(custom_plot_function(memory_data[sender_agent],sender_agent,**custom_plot_parameters))`

would it allow to return several Scatters instead of just one.

**Comment by bangxiangyong** [comment]
Hi there, thanks for raising this issue. The recent commits have been refactored and no longer has the line 
`data.append(custom_plot_function(memory_data[sender_agent],sender_agent,**custom_plot_parameters))`

Nonetheless, the ability to return more than one scatter is already available and thanks to this issue, i've committed an example to illustrate this.

https://github.com/bangxiangyong/agentMET4FOF/blob/develop/agentMET4FOF_tutorials/plotting/custom_memory_multiple_plot.py

In short, in your custom plot function, you can return multiple scatters in the form list by:

```
def custom_create_monitor_graph(data, sender_agent, xname='Time',yname='Y', noise_level=0.1):
    """
    Parameters
    ----------
    data : dict or np.darray
        The data saved in the MonitorAgent's memory, for each Inputs (Agents) it is connected to.
    sender_agent : str
        Name of the sender agent
    **kwargs
        Custom parameters.
        In this example, xname, yname and noise_level are the keys of the data in the Monitor agent's memory.
    """
    if xname and yname:
        x = data[xname]
        y = data[yname]
    else:
        x = np.arange(len(data))
        y = data

    trace = [go.Scatter(x=x, y=y+np.random.randn(*y.shape)*noise_level,mode="lines", name=sender_agent) for i in range(3)]
    return trace

```
