### ISSUE TITLE
Read the docs generation for agents and streams modules are not working

### ISSUE THREAD

**Issue by BjoernLudwigPTB** [bangxiangyong/agentMET4FOF#14]
At the moment the two links targets on the [docs startpage](https://agentmet4fof.readthedocs.io/en/latest/)
[agentMET4FOF agents](https://agentmet4fof.readthedocs.io/en/latest/agentMET4FOF%20agents.html)
[agentMET4FOF streams](https://agentmet4fof.readthedocs.io/en/latest/agentMET4FOF%20streams.html)
are empty. We have to check the according [rst-files](https://github.com/bangxiangyong/agentMET4FOF/tree/master/docs) and repair this. The autodocs were their earlier.

**Comment by bangxiangyong** [comment]
I noticed the docs to be empty as well, do you know what happened?

**Comment by BjoernLudwigPTB** [comment]
> 
> 
> I noticed the docs to be empty as well, do you know what happened?

No I don't but will investigate later today...
