### ISSUE TITLE
remove previous buffer data

### ISSUE THREAD

**Issue by majidam20** [bangxiangyong/agentMET4FOF#16]
i have buffered data and send to agent, but i want to after each new sending, perevious data romves , i mean remove last buffer and replace with new data.

**Comment by bangxiangyong** [comment]
Hi Majid,
I have implemented buffering methods on both sides: 

1. Sensor agent - store data in message buffer before sending off 
2. Monitor agent - store incoming data in memory, and removes the oldest buffer when it is beyond the specified memory buffer size.

An example can be found here: 
https://github.com/bangxiangyong/agentMET4FOF/blob/feature/hardware_sensors/examples/SENSORS/buffer_sensor.py

**Comment by BjoernLudwigPTB** [comment]
We need to confirm if Majid still works with the agents, and if so, if there is still anything to do.

**Comment by BjoernLudwigPTB** [comment]
This was introduced in e26f09310a5bb5c0ef85ecab3b9f9005dfe67439 and already merged to devel in 96be66d81756816484605fac166ba15324c9ce8b.

**Comment by BjoernLudwigPTB** [comment]
I cannot really determine, which code contributes to the actual resolving of the issue, but as far as I can see, the example implementation meets the requirements. I told @majidam20 to reopen this issue once he gets back to the desired functionality and finds, that there is still something missing.
