### ISSUE TITLE
Enhance tutorials by adding even more descriptive comments

### ISSUE THREAD

**Issue by BjoernLudwigPTB** [bangxiangyong/agentMET4FOF#21]
The tutorials are already well documented, but we could add more comments in the code. This could help us to clarify the process and make it even easier to get started.

**Comment by bangxiangyong** [comment]
I'm thinking of writing some short tutorials in the readthedocs panels. 

Even more ambitious could be short tutorial videos (1-5min) can be recorded with explanations and uploaded on youtube or something.

**Comment by BjoernLudwigPTB** [comment]
So starting to work on that means as well to better structurize ReadtheDocs.org?!

**Comment by BjoernLudwigPTB** [comment]
We keep tutorials and examples at one place.

**Comment by BjoernLudwigPTB** [comment]
In the meantime we added quite somewhat more text and restructured the tutorials as well as better integrated them into the docs. This should be resolved by now.
