### ISSUE TITLE
Enhance plotting possibilities of MonitorAgents

### ISSUE THREAD

**Issue by mgrub** [bangxiangyong/agentMET4FOF#32]
It would be nice, if the function `create_monitor_data` (used [here](https://github.com/bangxiangyong/agentMET4FOF/blob/develop/agentMET4FOF/dashboard/Dashboard.py#L385) and defined [here](https://github.com/bangxiangyong/agentMET4FOF/blob/develop/agentMET4FOF/dashboard/LayoutHelper.py#L31)) can be extended to allow for user-provided x values.

This would help with plotting infinite streams of time-series. 

The new function could look something like this: (old behaviour is obtainable by explicitly setting `xname` or `yname` to `None`)

``` python
def create_monitor_data(data, xname="time", yname="data", label="Monitor Data"):
    if xname and yname:
        x = data[xname]
        y = data[yname]
    else:
        x = np.arange(len(data))
        y = data

    trace = go.Scatter(x=x, y=y,mode="lines", name=label)
    return trace
```

**Comment by bangxiangyong** [comment]
Thanks for the suggestion, I definitely agree with the idea. At the moment, the user doesn't have direct access to the `create_monitor_data` function and it is only used to automatically generate graphs from the Monitor Agent's `memory` which is basically a buffer.

I'm not sure what's a more fluid way to provide the user a way to access the `xname` or even the `create_monitor_data` function. I'll need to give this a slightly longer thought.

**Comment by BjoernLudwigPTB** [comment]
> Thanks for the suggestion, I definitely agree with the idea. At the moment, the user doesn't have direct access to the `create_monitor_data` function and it is only used to automatically generate graphs from the Monitor Agent's `memory` which is basically a buffer.
> 
> I'm not sure what's a more fluid way to provide the user a way to access the `xname` or even the `create_monitor_data` function. I'll need to give this a slightly longer thought.

btw: I did not look at the code in depth, but if the user is not supposed to access `create_monitor_data` directly, that should be expressed by renaming it to `_create_monitor_data` according to [PEP8](https://www.python.org/dev/peps/pep-0008/#descriptive-naming-styles) the bit about *weak internal use*.

**Comment by mgrub** [comment]
Is it possible/feasible to put the dashboard into a class, with `create_monitor_data` as a member of that class? Then a user could inherit its own `CustomDashboard` with customized plotting behavior.

**Comment by bangxiangyong** [comment]
@mgrub that's a good suggestion, we've open a new issue in relation to this #38 . Will work on this till next week.

**Comment by bangxiangyong** [comment]
Implemented this with an example script too. 

https://github.com/bangxiangyong/agentMET4FOF/pull/33/commits/7b0fe540088cec209af55feccb52f1d797d86ccc

**Comment by bangxiangyong** [comment]
Any custom plot function will be provided via an instantiated MonitorAgent instead of the whole dashboard itself.

**Comment by BjoernLudwigPTB** [comment]
@mgrub unfortunately it was not easily possible to cherry-pick the according changes properly. So please have a look at the commit and the [custom dashboard](https://github.com/bangxiangyong/agentMET4FOF/commit/7b0fe540088cec209af55feccb52f1d797d86ccc#diff-f47f83ea1f25f7211dc39b5ab136e204) and check if something else is needed. Please drop a note here or in the according PR #33 to  let us know, what you think.

**Comment by mgrub** [comment]
@BjoernLudwigPTB : no problem, I did not encounter any problems at all using the current feature/ml branch. 

@bangxiangyong : I was able to test the new custom-plot-feature in my setup and it seems to be working fine. Especially the provided example was helpful to get started quickly. :+1:
