### ISSUE TITLE
Send a Pull Request to Haris with the methods in zema_feature_extract.py

### ISSUE THREAD

**Issue by BjoernLudwigPTB** [bangxiangyong/agentMET4FOF#34]
We rather want to use the methods Haris already prepared in his subfolder [methods](https://github.com/harislulic/ZeMA-machine-learning-tutorials/tree/master/methods) by transferring our methods in [zema_feature_extract.py](https://github.com/bangxiangyong/agentMET4FOF/blob/master/examples/ZEMA_EMC/zema_feature_extract.py) and then reusing them by introducing his code as a submodule in [ZEMA_EMC](https://github.com/bangxiangyong/agentMET4FOF/blob/master/examples/ZEMA_EMC).

**Comment by bangxiangyong** [comment]
Initiated a pull request which essentially creates a folder with the classes in feature_extract.py.

https://github.com/harislulic/ZeMA-machine-learning-tutorials/pull/31
