### ISSUE TITLE
Refactor Dashboard into one class

### ISSUE THREAD

**Issue by BjoernLudwigPTB** [bangxiangyong/agentMET4FOF#38]
This will automatically resolve #32 by the proposed overwriting mechanism.

**Comment by bangxiangyong** [comment]
Refactored into a new class : AgentDashboard. However, have not provided an option to provide custom plotting function yet. #32 is not automatically resolved.. 

https://github.com/bangxiangyong/agentMET4FOF/commit/418f2b206f4aa1097e1941fe976035daa4a51557
