### ISSUE TITLE
More explanation on the `memory` and the `update_data_memory` function used

### ISSUE THREAD

**Issue by bangxiangyong** [bangxiangyong/agentMET4FOF#45]
A separate tutorial on this will be helpful to illustrate how the data memory is used.

**Comment by BjoernLudwigPTB** [comment]
You find the sampe implementation in [buffer_sensor.py](https://github.com/bangxiangyong/agentMET4FOF/blob/b4715072933881844d8c66c61c4ceaea0cd7e085/examples/SENSORS/buffer_sensor.py#L27) and as part of #65 we should deal with this issue as well.

**Comment by bangxiangyong** [comment]
`update_data_memory` has been renamed to `store`, and an entire AgentBuffer class is created along with tutorials to illustrate its use:

https://github.com/bangxiangyong/agentMET4FOF/commit/0e1823a6b4e2ce31a58b5f3da5fb21a4875b2b57
