### ISSUE TITLE
Modularised plotting

### ISSUE THREAD

**Issue by bangxiangyong** [bangxiangyong/agentMET4FOF#53]
Considerations:
1. Zooming/Panning/etc. on an interactive
2. A clear/standardised architecture
3. Types of plots
4. Supporting the web visualisation

**Comment by BjoernLudwigPTB** [comment]
Maybe [mpld3](https://mpld3.github.io/) can help?

**Comment by bangxiangyong** [comment]
There are 3 ways to include matplotlib figures in the web dashboard powered by plotly:

1. convert to static image (existing method: easiest and exact but no interactivity)
2. convert to plotly figure via tls.mpl_to_plotly (fully interactive, but not all matplotlib figures are compatible such as boxplots, piecharts,..)
3. mpld3. This requires some hack to work with current dashboard, but making good progress.. (sufficient interactivity, wide compatibility with most matplotlib figures)

perhaps then, there should be an option for users to switch from 1 method to the other.

**Comment by bangxiangyong** [comment]
In agentMET4FOF context, there are probably 3 contexts which custom plots could take place:
1. Send plot figures from data processing/streaming agents to Monitor agent
2. Plotting function supplied with Monitor agent's init_parameters, and actual plotting is based on Monitor agent's `memory` data
3. Offline - ML experiments for comparing results of ML pipelines performances/outputs

**Comment by bangxiangyong** [comment]
- branch out option 1. and 2. 
- commit the progress with mpld3

**Comment by bangxiangyong** [comment]
- Document the options of 1. sending plot figures, or 2. plot within the monitor agents' memory
- maintain these two options
- write tutorials on these

**Comment by BjoernLudwigPTB** [comment]
> For the matplotlib:
> 
>     * branch out the options to choose 1. or 2.
> 
>     * commit the progress with mpld3 and laeve it as draft, so that it will be tracked

I would describe my suggestion with the words:

- push the according branch (dealing with all three options, as far as I understood)
- create a Pull Request for this branch
- either revert the commits introducing `mpld3`  if they were confined to the third option or just remove the according snippets from the code in one commit with a self-explaining message telling clearly when we dropped the changes related to its use
- merge the Pull Request after properly reviewing the left-overs and desired changes

This way we can properly proceed with this issue, resolve it and we do not loose the first try of introducing `mpld3`, which was promising.

**Comment by bangxiangyong** [comment]
Thanks for improving the clarity!

**Comment by bangxiangyong** [comment]
An example of how to provide custom plot of plotly can be provided here:

https://github.com/bangxiangyong/agentMET4FOF/blob/develop/examples/custom_dashboard.py

**Comment by bangxiangyong** [comment]
addressed here, within the `send_plot` function of base agent class:

https://github.com/bangxiangyong/agentMET4FOF/blob/custom_plots/agentMET4FOF/agents.py
