### ISSUE TITLE
Documentation of ML Experiments

### ISSUE THREAD

**Issue by bangxiangyong** [bangxiangyong/agentMET4FOF#54]
The documentation of components for ML experiments is not complete, and the structure is quite scattered (agents.py , develop.* , etc). 

The clarity can be improved by having more explanations and should probably be self-contained as a separate component?

**Comment by bangxiangyong** [comment]
Also, the data structure of ML experiments was not documented.

**Comment by BjoernLudwigPTB** [comment]
@bangxiangyong This issue should now be reopened in the new repository, right?

**Comment by bangxiangyong** [comment]
Yes that is true.

**Comment by bangxiangyong** [comment]
Since we have refactored the ML extension into another repo, we'll discuss and resolve it there.
