### ISSUE TITLE
Struggle to run dashboard on Windows machine

### ISSUE THREAD

**Issue by BjoernLudwigPTB** [bangxiangyong/agentMET4FOF#58]
There seems to be a problem with running the agents on Windows with Python 3.8.1 and `multiprocess==0.70.9`. A colleague gets the following error on execution of tutorial 1:

```bash
Starting NameServer...
Broadcast server running on 0.0.0.0:9091
NS running on 127.0.0.1:3333 (127.0.0.1) 
URI = PYRO:Pyro.NameServer@127.0.0.1:3333
INFO [2020-04-15 10:11:08.404372] (AgentController): INITIALIZED
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'multiprocess'
INFO [2020-04-15 10:11:30.828139] (SineGeneratorAgent_1): INITIALIZED
INFO [2020-04-15 10:11:39.270462] (MonitorAgent_1): INITIALIZED
[2020-04-15 10:11:39.358227] (SineGeneratorAgent_1): Connected output module: MonitorAgent_1
SET STATE:   Running
[2020-04-15 10:11:39.868856] (SineGeneratorAgent_1): Pack time: 0.0
[2020-04-15 10:11:39.869853] (SineGeneratorAgent_1): Sending: [0.]
[2020-04-15 10:11:39.869853] (MonitorAgent_1): Received: {'from': 'SineGeneratorAgent_1', 'data': array([0.]), 'senderType': 'SineGeneratorAgent', 'channel': 'default'}
[2020-04-15 10:11:39.869853] (MonitorAgent_1): Tproc: 0.0
```
On the same machine it is working with Python 3.7.7 and `multiprocess==0.70.7`. We haven't checked the multiprocess issues yet and he will continue with the working 3.7.7 configuration, so for now there is no further investigation.

**Comment by BjoernLudwigPTB** [comment]
@bangxiangyong Say, is there any reason, why we use a fork [multiprocess](https://pypi.org/project/multiprocess/) of the built-in library [multiprocessing](https://docs.python.org/3/library/multiprocessing.html)? Right now I am testing and it appears, as if the used functionality is provided by the official `multiprocessing` as well. I am sending a PR to investigate the issue in a short while.

**Comment by mgrub** [comment]
Hi guys, 

I tested the changes made in branch `exchange_multiprocess_by_official_multiprocessing` and the dashboard now works fine when running the `tutorial_1_generator_agent.py`.

System details:
OS: Windows 10 Pro (10.0.18363 Build 18363)
Python: 3.8.1 64-bit

------

Note:
I had to remove some dependecies from the requirements.txt, to successfully set up a new virtual environement on my windows machine.
matplotlib ~3.1.0~
~scikit-multiflow~
~torch~
~torchvision~

------

```
>>>pip list
Package              Version
-------------------- ------------
backcall             0.1.0
Brotli               1.0.7
click                7.1.2
cloudpickle          1.4.1
colorama             0.4.3
cycler               0.10.0
dash                 1.11.0
dash-core-components 1.9.1
dash-cytoscape       0.1.1
dash-html-components 1.0.3
dash-renderer        1.4.0
dash-table           4.6.2
decorator            4.4.2
dill                 0.3.1.1
Flask                1.1.2
Flask-Compress       1.5.0
future               0.18.2
ipykernel            5.2.1
ipython              7.13.0
ipython-genutils     0.2.0
itsdangerous         1.1.0
jedi                 0.17.0
Jinja2               2.11.2
joblib               0.14.1
jupyter-client       6.1.3
jupyter-core         4.6.3
kiwisolver           1.2.0
MarkupSafe           1.1.1
matplotlib           3.2.1
networkx             2.4
numpy                1.18.3
osbrain              0.6.5
pandas               1.0.3
parso                0.7.0
pickleshare          0.7.5
pip                  19.2.3
plotly               4.6.0
prompt-toolkit       3.0.5
Pygments             2.6.1
pyparsing            2.4.7
Pyro4                4.80
python-dateutil      2.8.1
pytz                 2020.1
pywin32              227
PyYAML               5.3.1
pyzmq                19.0.0
retrying             1.3.3
scikit-learn         0.22.2.post1
scipy                1.4.1
serpent              1.30.2
setuptools           41.2.0
six                  1.14.0
tornado              6.0.4
traitlets            4.3.3
wcwidth              0.1.9
Werkzeug             1.0.1
```

**Comment by BjoernLudwigPTB** [comment]
@bangxiangyong So we now know, how to fix the issue mentioned above... Now we just need to make sure not to introduce a new one. :wink:

**Comment by BjoernLudwigPTB** [comment]
> I tested the changes made in branch `exchange_multiprocess_by_official_multiprocessing` and the dashboard now works fine when running the `tutorial_1_generator_agent.py`.

Thanks a lot, especially for the additional input.

**Comment by BjoernLudwigPTB** [comment]
@bangxiangyong this needs some decision as well.

**Comment by BjoernLudwigPTB** [comment]
> @bangxiangyong Say, is there any reason, why we use a fork [multiprocess](https://pypi.org/project/multiprocess/) of the built-in library [multiprocessing](https://docs.python.org/3/library/multiprocessing.html)? Right now I am testing and it appears, as if the used functionality is provided by the official `multiprocessing` as well. I opened PR #75 to investigate the issue.

@bangxiangyong This needs some decision as well... :wink:

**Comment by BjoernLudwigPTB** [comment]
We agreed on reviewing the associated PR and merge the use of the built-in [multiprocessing](https://docs.python.org/3/library/multiprocessing.html) eventually.
