### ISSUE TITLE
Extract all examples/use cases into seperate repositories and clean up clutter

### ISSUE THREAD

**Issue by BjoernLudwigPTB** [bangxiangyong/agentMET4FOF#65]
We tried that in #50 and found it very promising. The next extractions might be:

- `ml_uncertainty`
- `demo`
- `ML`
- `ML_EXPERIMENTS`
- `SENSORS`
- `ZEMA_EMC`
- ... whatever could be moved from develop.

After that we can clean up the docs and requirements.txt and win

- significantly increased overview
- probably higher coverage
- a much clearer structure
- more presentable, accessible results, possibly with own DOIs and future citations.

**Comment by BjoernLudwigPTB** [comment]
The repos we will create and the according subfolders of _agentMET4FOF_ are

- _ML_Experiments_ and _ml_uncertainty_
- 

We want to add documentation pages for the following examples:

- `examples.demo.run_dashboard.py`

**Comment by BjoernLudwigPTB** [comment]
> ## Seperate repos
> The repos we will create and the according subfolders of _agentMET4FOF_ are
> 
> * [x]  ZEMA_BNN ([new repo you can find here](https://github.com/Met4FoF/agentMET4FOF_bayesian_neural_network_ZeMA))
> * [x]  ZEMA_EMC ([new repo you can find here](https://github.com/Met4FoF/agentMET4FOF_ZeMA_emc))
> * [ ]  _ml_uncertainty_

@bangxiangyong seemingly we made a mistake here, since _ml_uncertainty_ is heavily used in _ML_EXPERIMENTS_, which we want to transform into a tutorial inside _agentMET4FOF_. This would mean, we cannot extract _ml_uncertainty_ and it would mean, we will need pytorch as a dependency of _agentMET4FOF_ which we should try to avoid, because it imposes difficulties for us during the packaging and for the users during the installation.

What would you suggest?

**Comment by BjoernLudwigPTB** [comment]
@bangxiangyong since I need some input here, could we maybe meet tomorrow for a short while to keep going with this?

**Comment by bangxiangyong** [comment]
sorry for the late reply, just saw this and the previous one comment awhile ago. 

Yes, i think it is quite tricky, since in all the examples i have used BNN it seems. I think we can replace BNN with some other models in sklearn for the examples and still illustrate the same points. Thats a valid suggestion to have agentMET4FOF_ml, but not at this point, as for now, i'd try to keep ML tied in as much as possible with the agents.

it'll be tricky for me tomorrow, can we meet on Friday noon++ instead?

**Comment by BjoernLudwigPTB** [comment]
> sorry for the late reply, just saw this and the previous one comment awhile ago.
> 
> Yes, i think it is quite tricky, since in all the examples i have used BNN it seems. I think we can replace BNN with some other models in sklearn for the examples and still illustrate the same points. Thats a valid suggestion to have agentMET4FOF_ml, but not at this point, as for now, i'd try to keep ML tied in as much as possible with the agents.
> 
> it'll be busy for me tomorrow, can we meet on Friday noon++ instead?

Well, if we can drop `scikit-multiflow` and `pytorch` as dependencies, there is no real reason to split up something. The suggestion was meant to allow for keeping `pytorch` inside of the agents, but if you see a way, to just get rid of that in the core, like replace _ml_uncertainty_ in _ML_EXPERIMENTS_ by `scikit-learn`-internals, that would already solve the issue.

**Comment by BjoernLudwigPTB** [comment]
# TODO for @BjoernLudwigPTB 

- Move `develop.ML_Experiment.py` to agentMET4FOF now

**Comment by BjoernLudwigPTB** [comment]
# TODO for @bangxiangyong 

- [ ] Rewrite the `exmples.ML_EXPERIMENT` tutorial to get rid of _ml_uncertainty_ and _pytorch_ together with it

**Comment by bangxiangyong** [comment]
The examples.custom_dashboard.py has been moved into a set of tutorials for plotting:
https://github.com/bangxiangyong/agentMET4FOF/pull/114/commits/f7fa5dc2f103edc9489317353da6f4e01bbce921
