### ISSUE TITLE
Check if we really need matplotlib==3.1.0

### ISSUE THREAD

**Issue by BjoernLudwigPTB** [bangxiangyong/agentMET4FOF#74]
We should check if by now we could drop the constraint on `matplotlib==3.1.0` not to loose compatibility with newer Python versions.

@bangxiangyong could you provide a test, which checks for the reason of the constraint so we can test if an upgrade would harm the agents?

**Comment by bangxiangyong** [comment]
i forgot the specific reason to have this version of matplotlib...

**Comment by BjoernLudwigPTB** [comment]
> i forgot the specific reason to have this version of matplotlib...

Should we then just remove the restriction, update our venvs and keep a watchful eye on any unexpected behavior?

**Comment by BjoernLudwigPTB** [comment]
After our discussion today I will just change it and merge.
