### ISSUE TITLE
agentMET4FOF.agents classes need class docstring

### ISSUE THREAD

**Issue by BjoernLudwigPTB** [bangxiangyong/agentMET4FOF#78]
The following classes need class docstrings:

- [TransformerAgent](https://github.com/bangxiangyong/agentMET4FOF/blob/05cfbe9c00ede71730eed01c5a6e0efed0d9e931/agentMET4FOF/agents.py#L1015)
- [_Logger](https://github.com/bangxiangyong/agentMET4FOF/blob/05cfbe9c00ede71730eed01c5a6e0efed0d9e931/agentMET4FOF/agents.py#L1368)
- [AgentPipeline](https://github.com/bangxiangyong/agentMET4FOF/blob/05cfbe9c00ede71730eed01c5a6e0efed0d9e931/agentMET4FOF/agents.py#L1083)

**Comment by bangxiangyong** [comment]
Since the `TransformerAgent` and `AgentPipeline` are moved to ML extension repository, we shall handle them there.  https://github.com/bangxiangyong/agentMET4FOF_ml_extension/issues/2
For the _Logger agent, i will provide it soon.

**Comment by BjoernLudwigPTB** [comment]
> Since the `TransformerAgent` and `AgentPipeline` are moved to ML extension repository, we shall handle them there. [bangxiangyong/agentMET4FOF_ml_extension#2](https://github.com/bangxiangyong/agentMET4FOF_ml_extension/issues/2)
> For the _Logger agent, i provide it via [9e6312a](https://github.com/bangxiangyong/agentMET4FOF/commit/9e6312a743ffed34467d187c633f2d0b3b3c2fbf)

So this will beresolved after merging #116, right?
