### ISSUE TITLE
Get rid of develop folder before the SMSI tutorial

### ISSUE THREAD

**Issue by bangxiangyong** [bangxiangyong/agentMET4FOF#83]
we can open a branch and remove the develop folder asap

this is part of #65

**Comment by BjoernLudwigPTB** [comment]
Specifically buffer_deque.py needs to be removed and before that branched out like `feature/mpld3`.

**Comment by BjoernLudwigPTB** [comment]
> Specifically `buffer_deque.py` needs to be removed and before that branched out like `feature/mpld3`.

The [branch is created](https://github.com/bangxiangyong/agentMET4FOF/tree/feature/buffer) and PR #96 is opened. The rest of this is requires a careful extraction of develo/ML_Experiment. Since we deal with this so comprehensively in #65, I will close this one.
