### ISSUE TITLE
Default values for AgentMET4FOF.memory_buffer_size and AgentMET4FOF.buffer_size not set

### ISSUE THREAD

**Issue by BjoernLudwigPTB** [bangxiangyong/agentMET4FOF#88]
I am not so clear about the meaning of [`agentMET4FOF.agents.AgentMET4FOF.buffer_size`](https://github.com/bangxiangyong/agentMET4FOF/blob/develop/agentMET4FOF/agents.py#L194) and [`agentMET4FOF.agents.AgentMET4FOF.memory_buffer_size`](https://github.com/bangxiangyong/agentMET4FOF/blob/develop/agentMET4FOF/agents.py#L561). Shouldn't we introduce those parameters in the constructor and document their meaning?

**Comment by bangxiangyong** [comment]
You are right. The `buffer_size` which is used as part of `buffer_filled` is actually not initialised anywhere and upon investigation, it was originally implemented here: https://github.com/bangxiangyong/agentMET4FOF/blob/b4715072933881844d8c66c61c4ceaea0cd7e085/examples/SENSORS/buffer_sensor.py#L27

This has relation to: https://github.com/bangxiangyong/agentMET4FOF/issues/45

**Comment by bangxiangyong** [comment]
default_memory_size can be provided on_init of agents, and hence via AgentNetwork.add_agent : https://github.com/bangxiangyong/agentMET4FOF/commit/b0ec79743daca466000f45ac33619c39095340c5
