### ISSUE TITLE
Missing docstring or explanatory comment for property buffer_filled

### ISSUE THREAD

**Issue by BjoernLudwigPTB** [bangxiangyong/agentMET4FOF#89]
Although it is quite obvious, we should add a short comment about the meaning of the property [agentMET4FOF.agents.AgentMET4FOF.buffer_filled](https://github.com/bangxiangyong/agentMET4FOF/blob/develop/agentMET4FOF/agents.py#L193).

**Comment by bangxiangyong** [comment]
resolved here: https://github.com/bangxiangyong/agentMET4FOF/pull/116
