### ISSUE TITLE
Undefined variable agentmet4fof_module in agentMET4FOF/dashboard/Dashboard_agt_net.py

### ISSUE THREAD

**Issue by BjoernLudwigPTB** [bangxiangyong/agentMET4FOF#90]
I suspect there is a bug in [Dashboard_agt_net.py](https://github.com/bangxiangyong/agentMET4FOF/blob/develop/agentMET4FOF/dashboard/Dashboard_agt_net.py#L253) as I do not see, where the `agentmet4fof_module` might be initialized (or rather imported).

**Comment by bangxiangyong** [comment]
It is quite strange, the way the callback works, so actually the `agentmet4fof_module` is imported when initialised in this file instead:
https://github.com/bangxiangyong/agentMET4FOF/blob/develop/agentMET4FOF/dashboard/Dashboard_Control.py

i will try and see an error is raised with the clicking the add dataset button.

**Comment by BjoernLudwigPTB** [comment]
> It is quite strange, the way the callback works, so actually the `agentmet4fof_module` is imported when initialised in this file instead:
> https://github.com/bangxiangyong/agentMET4FOF/blob/develop/agentMET4FOF/dashboard/Dashboard_Control.py
> 
> i will try and see an error is raised with the clicking the add dataset button.

Ah yes, I noticed something similar in another project before. Yes, please check this and close this one, if everything is okay.

**Comment by bangxiangyong** [comment]
you are right..apparently it did raise an error, upon clicking on `Add Datastream Agent` on the right panel:

`NameError: name 'agentmet4fof_module' is not defined`

**Comment by BjoernLudwigPTB** [comment]
> you are right..apparently it did raise an error, upon clicking on `Add Datastream Agent` on the right panel:
> 
> `NameError: name 'agentmet4fof_module' is not defined`

You can add the missing import to #92, because we are working on this file anyway.
