### ISSUE TITLE
Missing documentation for new dashboard feature allowing to send several plots at once

### ISSUE THREAD

**Issue by BjoernLudwigPTB** [bangxiangyong/agentMET4FOF#93]
We prepared a PR #92, introducing the discussed change and an according test. What is missing for now is simply the user documentation of the feature itself.

**Comment by bangxiangyong** [comment]
I've prepared a tutorial which illustrate this feature: list_of_plots.py
https://github.com/bangxiangyong/agentMET4FOF/pull/114/commits/f7fa5dc2f103edc9489317353da6f4e01bbce921
